import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'EasyDoc | Book Doctors',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {




  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col items-center`}>
        {/* <nav className='drop-shadow-xl min-w-full h-5 mb-20'>
          <Navbar />
        </nav> */}
        <main
          className='h-full w-full'
        >
          {children}
        </main>


      </body>
    </html>
  )
}
